version: '3.9'

services:
  productivity-app:
    image: productivity-app:SNAPSHOT
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11.21-bullseye
    ports:
      - "5432:5432"
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb