services:
  productivity-app:
    container_name: app
    image: productivity-app:SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: java -jar -Dspring.profiles.active=dev,postgres app.jar
    environment:
      - TZ=${SYSTEM_TIME_ZONE}
    networks:
      - monitoring
  postgres:
    container_name: db
    hostname: postgres
    image: postgres:11.21-bullseye
    ports:
      - "5432:5432"
    volumes:
      - data-3.6:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
      - TZ=${SYSTEM_TIME_ZONE}
    networks:
      - monitoring
    expose:
      - "5432"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - monitoring
volumes:
  data-3.6:
    external: true
networks:
  monitoring: