version: '3.9'

services:
  productivity-app:
    image: productivity-app:SNAPSHOT
    ports:
      - "8080:8080"
  postgres:
    image: postgres:11.21-bullseye
    ports:
      - "6000:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb