services:
  productivity-app:
    container_name: app
    image: productivity-app:SNAPSHOT
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: db
    hostname: postgres
    image: postgres:11.21-bullseye
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
volumes:
  data:
    external: true