version: "3.9"
services:
  productivity-app:
    container_name: app
    image: productivity-app:SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: java -jar -Dspring.profiles.active=dev,postgres app.jar
  postgres:
    container_name: db
    hostname: postgres
    image: postgres:11.21-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres-v2-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
volumes:
  postgres-data:
    external: true
  postgres-v2-data:
    external: true
